# Generated by Django 5.1.2 on 2024-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0004_alter_video_options_alter_video_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
