# Generated by Django 5.1.2 on 2024-10-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='video_manager.tag', verbose_name='Tags'),
        ),
    ]
