# Generated by Django 5.1.2 on 2024-10-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0006_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Curtidas'),
        ),
    ]
