# Generated by Django 5.1.2 on 2024-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0007_alter_video_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='published_date',
            new_name='published_at',
        ),
        migrations.AlterField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=False, editable=False, verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Curtidas'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Visualizações'),
        ),
    ]
