# Generated by Django 5.1.2 on 2024-10-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0008_rename_published_date_video_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(editable=False, verbose_name='Data de publicação'),
        ),
    ]
