# Generated by Django 5.1.2 on 2024-10-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0009_alter_video_is_published_alter_video_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de publicação'),
        ),
    ]
