# Generated by Django 5.1.2 on 2024-10-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0011_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/video_files/', verbose_name='Arquivo de vídeo'),
        ),
    ]
