# Generated by Django 5.1.2 on 2024-10-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0014_alter_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_files/', verbose_name='Arquivo de vídeo'),
        ),
    ]
